on: [pull_request, push]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: graalvm
      - uses: gradle/actions/setup-gradle@v4
      - run: gradle shadowJar
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{github.run_number}}
          files: build/libs/iotcraft.jar
      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: Yb0wYJtD
          modrinth-token: ${{secrets.MODRINTH_TOKEN}}
          files: build/libs/iotcraft.jar
          name: ""
